Basic tests:
        All correctness tests passed
        Total Messages Between Replicas: 1296 < 3000, Passed
        Total Failures and Unanswered Requests: 0 < 1, Passed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.000815153121948 < 0.002, Passed
        No drops, no failures, 80% read                                 [PASS]  Performance Tiers:  1
 1
 1
 1

        All correctness tests passed
        Total Messages Between Replicas: 3356 < 4000, Passed
        Total Failures and Unanswered Requests: 0 < 1, Passed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.000960111618042 < 0.001, Bonus!
        No drops, no failures, 20% read                                 [PASS]  Performance Tiers:  1
 1
 1
 0

Unreliable network tests:
*** Simulator Error - client received an incorrect value for a key: {"src": "0004", "dst": "001A", "MID": "Y9S1CIB426BGMTLO", "value": "6391fe2a734bcccbc9cad3146b2e490c", "type": "ok", "leader": "0004"}                                                                                                                                  
*** Simulator Error - client received an incorrect value for a key: {"src": "0004", "dst": "0019", "MID": "QCUOETBR4D0STGRW", "value": "79fd3416f00a9f0db686c9c60b297188", "type": "ok", "leader": "0004"}                                                                                                                                  
*** Simulator Error - client received an incorrect value for a key: {"src": "0004", "dst": "0019", "MID": "2MEWH2M8P7Z1W9DX", "value": "3f6abb8888a0b522e0acbb634e24533b", "type": "ok", "leader": "0004"}                                                                                                                                  
        Error: >0 incorrect responses to get()
        5% drops, no failures, 20% read                                 [FAIL]
        All correctness tests passed
        Total Messages Between Replicas: 3151 < 4500, Passed
        Total Failures and Unanswered Requests: 0 < 1, Passed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.000969886779785 < 0.001, Bonus!
        10% drops, no failures, 20% read                                [PASS]  Performance Tiers:  1
 1
 1
 0

        Error: insufficient get() requests were generated because insufficient put()s were accepted (12 > 105 * 0.10)
        15% drops, no failures, 20% read                                [FAIL]
Crash failure tests:
        All correctness tests passed
        Total Messages Between Replicas: 3348 < 4000, Passed
        Total Failures and Unanswered Requests: 0 < 1, Passed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.00113701820374 < 0.005, Passed
        No drops, 1 replica failure, 20% read                           [PASS]  Performance Tiers:  1
 1
 1
 1

        All correctness tests passed
        Total Messages Between Replicas: 3031 < 4000, Passed
        Total Failures and Unanswered Requests: 0 < 1, Passed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.00108480453491 < 0.005, Passed
        No drops, 2 replica failures, 20% read                          [PASS]  Performance Tiers:  1
 1
 1
 1

        All correctness tests passed
        Total Messages Between Replicas: 2458 < 4000, Passed
        Total Failures and Unanswered Requests: 20 >= 5, Failed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.00110411643982 < 0.005, Passed
        No drops, 1 leader failure, 20% read                            [PASS]  Performance Tiers:  1
 3
 1
 1

Traceback (most recent call last):
  File "./3700kvstore", line 76, in <module>
    msg_raw = sock.recv(32768)
socket.error: [Errno 104] Connection reset by peer
        All correctness tests passed
        Total Messages Between Replicas: 1692 < 1800, Bonus!
        Total Failures and Unanswered Requests: 26 >= 10, Failed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.000783205032349 < 0.005, Passed
        No drops, 2 leader failures, 20% read                           [PASS]  Performance Tiers:  0
 3
 1
 1

Partition tests:
*** Simulator Error - client received an incorrect value for a key: {"src": "0000", "dst": "001C", "MID": "RB3OPRJB5VH72UHR", "value": "10855e000d1b20f61fcd87700710d809", "type": "ok", "leader": "0000"}                                                                                                                                  
        Error: >0 incorrect responses to get()
        No drops, 1 easy partition, 20% read                            [FAIL]
*** Simulator Error - client received an incorrect value for a key: {"src": "0004", "dst": "001B", "MID": "AF7TGNXLWLXUGZFF", "value": "1d069f5289a7453c45996312f6652faa", "type": "ok", "leader": "0004"}                                                                                                                                  
        Error: >0 incorrect responses to get()
        No drops, 2 easy partitions, 20% read                           [FAIL]
        All correctness tests passed
        Total Messages Between Replicas: 2513 < 4000, Passed
        Total Failures and Unanswered Requests: 12018 >= 30, Failed
        Duplicate Responses to Clients: 0 < 2, Passed
        Median Response Latency to Clients: 0.000102996826172 < 0.00025, Bonus!
        No drops, 1 hard partition, 20% read                            [PASS]  Performance Tiers:  1
 3
 1
 0

*** Simulator Error - client received an incorrect value for a key: {"src": "0000", "dst": "001B", "MID": "Y7VIWF37KURR66NT", "value": "077221e70816b2d20058751439b0ba6e", "type": "ok", "leader": "0000"}                                                                                                                                  
        Error: >0 incorrect responses to get()
        No drops, 2 hard partitions, 20% read                           [FAIL]
Traceback (most recent call last):
  File "./test.py", line 91, in <module>
    ldr = open(LEADERBOARD_OUTPUT + getpass.getuser(), 'w')
IOError: [Errno 2] No such file or directory: '/course/cs3700f20/stats/project6/kali'
